language: node_js
node_js:
  - "9"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq awscli
script:
  - npm i -g electric-cli
  - npm install
  - electric build
  - aws s3 sync --region=us-west-2 dist/ s3://ivoryshield.io/
  - electric deploy -e ghpages
